#!/bin/sh

set -e

basedir=$(dirname `pwd`)

DEBVERSION=`head -1 $basedir/debian/changelog | cut '-d ' -f 2 | sed 's/[()]//g'`
VERSION=`expr $basedir : '.*-\([0-9][0-9a-z]*debian\)'`

REVISION=`expr $basedir : '.*debian\([0-9a-z\.]\+\)$'`

SEDRULE_FILENAME="-e s/__VER__/$VERSION/g -e s/\\.in$//"
SEDRULE_CONTENT="-e s/__DEBIANVER__/$DEBVERSION/g -e s/__FULLVER__/$VERSION.$REVISION/g -e s/__VER__/$VERSION/g"

for file in `find $basedir/debian -type f -name '*.in' -not -name control.in -not -name POTFILES.in`; do
	eval targetfile=`echo $file | sed $SEDRULE_FILENAME`
	sed $SEDRULE_CONTENT <$file >$targetfile
done

debconf2po-update

#for file in `find $basedir/debian -type f -name '*.in' -not -name control.in -not -name POTFILES.in`; do
#	eval targetfile=`echo $file | sed $SEDRULE_FILENAME`
#	rm -f $targetfile
#done
